### ISSUE TITLE
[HOOK-REGRESSION] #686 fix broke 5 TestSubagentTypePriority tests — mock stubs missing launched_agents kwarg

### ISSUE THREAD

**Issue by akaszubski** [akaszubski/autonomous-dev#690]
## Problem

The fix for issue #686 (wiring \`launched_agents\` into the ordering gate call site in \`unified_pre_tool.py\`) broke 5 pre-existing tests in \`TestSubagentTypePriority\`. The tests fail open with \`KeyError: 'target'\` because their mock stubs for \`check_ordering_prerequisites\` do not accept the new \`launched_agents\` keyword argument.

**Hook test suite baseline**: 14 pre-existing failures (8 batch_permission_approver + 6 unified_pre_tool).
**After batch #685/#686**: 13 failures total — but the composition changed:
- \`test_stale_state_file\` fixed (now passes) — #685 fix worked correctly
- 5 tests in \`TestSubagentTypePriority\` now fail — introduced by #686 fix
- Net: 14 → 13 failures, but 5 are new regressions masking the 6 pre-existing unified_pre_tool failures

**Repo**: autonomous-dev
**Session**: 2026-04-07T17:52:00

## Evidence

Failing tests:
```
FAILED tests/unit/hooks/test_native_tool_auto_approval.py::TestSubagentTypePriority::test_planner_prompt_mentioning_implementer_uses_subagent_type
FAILED tests/unit/hooks/test_native_tool_auto_approval.py::TestSubagentTypePriority::test_no_subagent_type_falls_back_to_text_extraction
FAILED tests/unit/hooks/test_native_tool_auto_approval.py::TestSubagentTypePriority::test_implementer_blocked_when_prerequisites_not_met
FAILED tests/unit/hooks/test_native_tool_auto_approval.py::TestSubagentTypePriority::test_multiple_agent_names_in_prompt_subagent_type_wins
FAILED tests/unit/hooks/test_native_tool_auto_approval.py::TestSubagentTypePriority::test_empty_subagent_type_falls_back_to_text_extraction
```

Root cause in test mocks:
```python
# Test mock (missing launched_agents):
def mock_check(target, completed, validation_mode=None):
    captured["target"] = target
    ...

# Actual call after #686 fix (unified_pre_tool.py line ~533):
check_ordering_prerequisites(target_agent, completed, validation_mode=mode, launched_agents=launched)
```

When the hook calls \`check_ordering_prerequisites\` with \`launched_agents=launched\`, Python raises \`TypeError: mock_check() got an unexpected keyword argument 'launched_agents'\`. The hook catches this and fails open with a warning, so \`captured["target"]\` is never set, causing \`KeyError: 'target'\` at the assertion.

Warning logged per test run:
```
WARNING unified_pre_tool.ordering: Pipeline ordering check failed open for tool='Agent': 
mock_check() got an unexpected keyword argument 'launched_agents'. If this involves 
security-auditor, the ordering guarantee is NOT enforced. Issue #669.
```

**Timeline**:
- \`e8df1fa\`: \`launched_agents\` param added to \`check_ordering_prerequisites\` signature (optional, defaulted to None)
- \`58c777f\`: \`TestSubagentTypePriority\` tests written — mock stubs did NOT include \`launched_agents\`
- \`727cda2\` (#686 fix): \`unified_pre_tool.py\` now passes \`launched_agents=launched\` at call site → tests fail

## Suggested Fix

Update all 5 mock stubs in \`TestSubagentTypePriority\` to accept \`**kwargs\` or explicitly add \`launched_agents=None\`:

```python
# Fix: accept the new kwarg
def mock_check(target, completed, validation_mode=None, launched_agents=None):
    captured["target"] = target
    ...
```

This is a 5-line fix across 5 test methods in \`tests/unit/hooks/test_native_tool_auto_approval.py\` (lines ~701, ~737, ~772, ~800, ~835).

**Plugin Version**: 3.50.0 (9345a58)

---
*Filed automatically by continuous-improvement-analyst*
