### ISSUE TITLE
Bare 'from conftest import' breaks CANONICAL_BASELINE_CMD collection — 51 tests invisible, produced a false dead-mechanism finding

### ISSUE THREAD

**Issue by akaszubski** [akaszubski/autonomous-dev#1666]
## Summary

Two test files use a bare `from conftest import ...`. That name binds to whichever `conftest.py`
pytest loaded first, so when `tests/unit` and `tests/integration` are collected together — which is
exactly the repo's own `CANONICAL_BASELINE_CMD` — both files raise `ImportError` and pytest aborts
collection with exit code 2. The result: **the canonical baseline command cannot collect at all**,
and 51 passing tests are invisible.

## Evidence (MEASURED 2026-08-25)

Collected together — aborts:

```
$ pytest tests/unit tests/integration -q --tb=line --co
ERROR tests/unit/genai/test_genai_client.py
ERROR tests/unit/genai/test_soft_failure_thresholds.py
!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!
=========== 12030 tests collected, 2 errors in 2.51s ===========
```

The error itself names the wrong conftest explicitly:

```
tests/unit/genai/test_genai_client.py:20: in <module>
    from conftest import GenAIClient, SoftFailureTracker, _extract_json_from_response
E   ImportError: cannot import name 'GenAIClient' from 'conftest'
    (/Users/akaszubski/Dev/autonomous-dev/tests/integration/conftest.py)
```

Collected alone — passes:

```
$ pytest tests/unit/genai/ -q --tb=no
51 passed, 1 warning in 6.65s
```

Single variable changed: the presence of `tests/integration` on the command line.

## Scope

Exactly 2 files repo-wide use this import form (`grep -rln '^from conftest import\|^import conftest' tests/`):

- `tests/unit/genai/test_genai_client.py:20`
- `tests/unit/genai/test_soft_failure_thresholds.py:19`

Both import from `tests/genai/conftest.py`, which defines `GenAIClient`, `SoftFailureTracker`,
`_load_thresholds`, `_extract_json_from_response`. `tests/unit/genai/` has no `__init__.py` and no
local `conftest.py`, so nothing anchors the bare name.

Introduced 2026-04-11 in 7f0f3e61 ("feat: add spec-blind validation and strengthen GenAI judges",
#772/#771). Pre-existing — not introduced by the #1579 or #1582 conftest work.

## Why this matters beyond 2 files

1. **It silently breaks the canonical baseline.** `pipeline_state.CANONICAL_BASELINE_CMD` is
   `['pytest','tests/unit','tests/integration','-q','--tb=no']`. Every `/implement` run captures its
   baseline with that command. It currently returns exit 2 and measures nothing.
2. **The `__COLLECTION_ERROR__` sentinel (#1533) is the only reason this was caught** — it refused to
   record a "0 failing tests" baseline. Without it the run would have treated an aborted collection
   as a green tree and classified every later failure as NEW. The sentinel worked; the underlying
   defect was never fixed.
3. **It produced a false "dead mechanism" finding.** `SoftFailureTracker` was recorded in
   `docs/experiments/GOAL_2026-08-24_enforcement-proven-everywhere.md` as requested by 0 tests and a
   deletion candidate. It is exercised by 51 passing tests. Acting on that line would have deleted
   them. A count taken over a population that failed to collect is the same defect as a pass over
   zero.

## Durable fix (fix the class, not the instance)

Do not just rename the import. The class is "a test file resolves a shared symbol through an
ambiguous bare module name." Options, preferred first:

- **A. Promote the shared symbols to a real importable module** — move `GenAIClient`,
  `SoftFailureTracker`, `_load_thresholds`, `_extract_json_from_response` out of
  `tests/genai/conftest.py` into e.g. `tests/genai/_genai_support.py`, and have both the conftest and
  the two unit tests import from that path. conftest.py stays fixtures-only, which is its contract.
- **B. Guard the class by construction** — add a check that fails when any file under `tests/`
  contains `^from conftest import` or `^import conftest`, so a third instance cannot appear.

## Test Scenarios

- [ ] `pytest tests/unit tests/integration -q --co` collects with **0 errors** (currently 2)
- [ ] `pytest tests/unit/genai/ -q` still passes 51/51 after the change
- [ ] The 51 tests are **present in the combined run** — assert the collected count rises by 51, by
      set membership not just total (`after − before` names the members)
- [ ] Negative control: reintroduce a bare `from conftest import` in a scratch file and confirm the
      new guard REFUSES it; confirm it PERMITS a normal `from tests.genai._genai_support import ...`
- [ ] `detect_capture_failure()` no longer returns `__COLLECTION_ERROR__` for the canonical command

## Acceptance Criteria

- [ ] Zero files under `tests/` use a bare `conftest` import
- [ ] `CANONICAL_BASELINE_CMD` collects cleanly and produces a real baseline
- [ ] A guard exists that blocks reintroduction, watched both refusing and permitting
- [ ] Regression test fails before the fix and passes after

**Comment by akaszubski** [comment]
Downstream consequence found 2026-08-25 while running a deletion pipeline: **the baseline-scope record is unusable, not just the baseline itself.**

`pipeline_state.record_baseline_scope()` validates the supplied command and returns `False` for anything that is not `CANONICAL_BASELINE_CMD` (`['pytest','tests/unit','tests/integration','-q','--tb=no']`). Since that exact command cannot collect — the bare-`conftest` import in this issue makes it exit 2 — there is currently **no command that both (a) produces a real measurement and (b) is accepted by the recorder**.

Measured just now:
- Canonical command → `__COLLECTION_ERROR__` (this issue).
- A working change-scoped perimeter (`tests/unit/hooks tests/unit/lib tests/regression tests/spec_validation`, ignoring the #1570 file) → **11,331 passed / 178 failing**, a usable baseline.
- `record_baseline_scope(state_path, <that perimeter command>, 11331)` → **`False`**. Refused.

So every `/implement` run right now either records nothing or records a scope it could not measure. The sentinel's `baseline_cmd` field is the contract STEP 8 uses to keep the implementer's pytest scope identical to the baseline's (#990); with no valid record, that contract is silently absent.

Not asking to widen this issue's scope — the fix is still the bare-`conftest` import. Noting it because it means the blast radius is larger than 51 invisible tests: it also disables the baseline-scope contract for every pipeline run until this lands.

**Comment by akaszubski** [comment]
Fixed in `ebbc61ba`, pushed to master.

Shared symbols relocated to `tests/genai/_genai_support.py`; `tests/genai/conftest.py` drops **583 → 69 lines** and now holds only the pytest hooks and fixtures that are its actual contract. Guard added at `tests/regression/test_issue_1666_no_bare_conftest_import.py` (55 lines, 3 test functions).

**Measured:**
- `pytest tests/unit tests/integration --collect-only -q` → **12,105 collected, 0 errors**. Previously exited 2 on the two `conftest` ImportErrors — this is the defect, gone.
- `pytest tests/unit/genai/ -q` → 51 passed, node-ID set **identical by `diff`**, not merely an equal count.
- `pytest tests/genai/ --collect-only` → 445 collected, 0 errors.
- Guard watched **refusing** `from conftest import Foo` and `import conftest`, and **permitting** a package-qualified import plus the differently-shaped near-miss `import conftest_helpers` that a naive prefix match would false-flag.

**A planned deletion was reversed by evidence, not by review.** The plan called `PROJECT_ROOT` dead on Serena's `find_referencing_symbols` ("no referencing symbol anywhere"). It has **33 live consumers**, every one a relative import (`from .conftest import PROJECT_ROOT`) the LSP did not follow. Deleting it would have broken all 33. The conftest re-exports it instead. Nothing in review caught this — a collection failure after the move did.

**Not claimed as fixed:** the downstream goal of making `record_baseline_scope` accept a real measured count is *not* met by this change, and for a reason worth recording separately — that function's count comes from a regex over source text, not from the command it records, and cannot report zero. Filed as #1678.

Out of scope and still broken, stated rather than absorbed: `tests/regression/test_issue_1570_multi_operand_write_targets.py` fails to collect on an unrelated `tool_intent` AttributeError.
